version: "3.9"

services:
  python-google-photos:
    build:
      context: ../src
      dockerfile: Dockerfile
    container_name: google-photos
    volumes:
      - ../src:/app
      - ../src/downloaded_albums:/app/downloaded_albums
      - ../script:/app/script
    working_dir: /app
    command: ["python", "app.py"]
    ports:
      - "5050:5050"
    networks:
      - shared_net
  pgsql_photos:
    image: postgres
    container_name: pgsql_photos
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photodatabase
    ports:
      - "5434:5432"
    volumes:
      - ../pg_data:/var/lib/postgresql/data
    networks:
      - shared_net

  line-reply-service:
    build:
      context: ../line_reply_service
    container_name: line-reply
    volumes:
      - ../line_reply_service:/app
    working_dir: /app
    command: ["python", "app.py"]
    ports:
      - "5002:5001"
    networks:
      - shared_net
volumes:
  pg_data:

networks:
  shared_net:
    external: true
